# Generated by Django 6.0 on 2025-12-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
