# Generated by Django 6.0 on 2025-12-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
