# Generated by Django 6.0 on 2025-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='Rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
