# Generated by Django 6.0 on 2026-01-07 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_bookstore_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='Bookname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Book name must contain only letters and spaces', regex='^[A-Za-z ]+$')]),
        ),
    ]
