# Generated by Django 6.0 on 2025-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviebooking',
            old_name='username',
            new_name='moviename',
        ),
        migrations.RemoveField(
            model_name='moviebooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='moviebooking',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='moviebooking',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='moviebooking',
            name='paymentmode',
        ),
        migrations.RemoveField(
            model_name='moviebooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='moviebooking',
            name='useremail',
        ),
        migrations.AddField(
            model_name='moviebooking',
            name='screenname',
            field=models.CharField(default='screen-1', max_length=100),
        ),
        migrations.AddField(
            model_name='moviebooking',
            name='showtime',
            field=models.CharField(default='screen-1', max_length=100),
            preserve_default=False,
        ),
    ]
