# Generated by Django 6.0 on 2026-01-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_hall_ticket', models.BooleanField(default=False)),
                ('attendance_percentage', models.IntegerField(default=0)),
                ('exam_fee_paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sign_up_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
