# Generated by Django 6.0 on 2025-12-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254, unique=True)),
                ('orderid', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentmode', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
