# Generated by Django 6.0 on 2025-12-22 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='currency',
            field=models.CharField(default='INR', max_length=50),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='transcationid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='orderid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
